### ISSUE TITLE
Provide build instructions

### ISSUE THREAD

**Issue by ErwanMAS** [fridtjof/ILO2RemCon#1]
Sorry for this question .

How i can compile this on a linux system ?

**Comment by ErwanMAS** [comment]
i reply to myself :
you need jdk 1.8.0 251

create a build folder

javac  -d ../build -classpath ../vendor/mjson-1.4.0.jar  *java com/hp/ilo2/remcons/*java

jar -cmf META-INF/MANIFEST.MF  ILO2RemCon.jar -C ../build  .

copy your java.security folder somewhere

modify the copy 

```
--- /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents//Home/jre/lib/security/java.security	2020-03-12 05:56:27.000000000 -0400
+++ ./java.security	2020-05-23 16:18:16.000000000 -0400
@@ -568,8 +568,7 @@
 #   jdk.certpath.disabledAlgorithms=MD2, DSA, RSA keySize < 2048
 #
 #
-jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
-    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224
+jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 768

 #
 # Algorithm restrictions for signed JAR files
@@ -644,8 +643,8 @@
 #
 # Example:
 #   jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048
-jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, \
-    EC keySize < 224, 3DES_EDE_CBC, anon, NULL
+
+jdk.tls.disabledAlgorithms=SSLv3, RC4, DH keySize < 768

 # Legacy algorithms for Secure Socket Layer/Transport Layer Security (SSL/TLS)
 # processing in JSSE implementation.

```
run 

java -Djava.security.properties=java.security  -jar ILO2RemCon.jar  IloHost Administrator IloPassord

**Comment by fridtjof** [comment]
Great to see you got it to work!

To answer the original question - the easiest way (that I'm using) is to build it using IntelliJ, for which the project files are included in the repository. Of course, I should add independent build instructions.

I'll leave this issue open to keep that in mind the next time I actually work on this project :)

**Comment by fridtjof** [comment]
Hi, we now have Gradle set up. Building should be as easy as running `./gradlew build`, followed by `./gradlew run` to run it
